POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Tinubu Hope of a Nation",
  "author": "Bayo M.",
  "url": "aso/me",
  "likes": 1,
  "userId": "68c1a3e13b4d70a86308d5cb"
}